### PR TITLE
Fix for large contact lists and Grandstream-Export

### PR DESCRIPTION
**Pull request by linuzer**
- large contact lists cannot be converted to XML the way it is implemented. As a quick-fix I added the LIBXML_PARSEHUGE option. Better would be IMHO a redesign to convert the XML in a streaming-way.
- export for Grandstream telephones didn't work (at least for my GRP-2612)
  * fix spell-error of AddressBook-attribute
  * added id-tag
  * limit to 1000 entries, since that is the hard limit of Grandstream-telephones.

### CODE REVIEW

**Comment by blacksenator** [comment]
Hi linuzer,
thank you very much for your contribution. I really appreciate your contribution. However, I would like to ask you not to mix different change areas in one pull request.
In detail:
- the XSL adjustments for Grandstream refer to mine - in this respect this part of the PR is correct here in my fork.
- your recommendation for the SimpleXMLElement belongs in andig's repository because it affects the master, which I use as a base. But: andig will only accept this change recommendation as a PR if it refers to a previously opened issue in which the specific problem is described. How big is your CardDAV file?
For example, I have had no problems with 1,500 contacts from an iCloud server.
I quickly tried to measure the memory volume with `memory_get_usage()`. Both for `$xml` and for `$body`. Measured before and after allocation I see only fractions of the MB.

**Comment by linuzer** [comment]
Hi blacksenator,
yes, I realised that it's a bad idea to mix up different issues and I wanted to make two PR out of this, but GitHub didn't allowed me to do ... at least in the PR-wizzard on the web page. But I can try again to split it up, it's better anyway... Probably I have to do it with git on the command line...

Regarding the LIBXML_PARSEHUGE: I received an error on that line, telling me that it is too big. I "only" have around 1150 contacts, but lots of them with images. I can try to reproduce the error, because it stated something about 64 MB.

Should I open up issues for both problems, one in your repo and the other in andig's one?

**Comment by linuzer** [comment]
I created an issue in andig's repository and will submit the PR to his repo. You will pull it from there, right?

[https://github.com/andig/carddav2fb/issues/238](url)

**Comment by linuzer** [comment]
I created an issue #6 and a PR #7
Hope, that's better.

**Comment by blacksenator** [comment]
Thumbs up

**Pull request closed without merging**
